packages:
  - 'packages/valibot'
  - 'packages/__tests__/core'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

nodeLinker: hoisted

minimumReleaseAge: 300

minimumReleaseAgeExclude:
  - '@bemedev/*'
